### PR TITLE
Add schema error if cannot generate form

### LINKED ISSUE #72: dropdown gets stuck a bit, bit buggy
https://user-images.githubusercontent.com/54760466/229176272-2d4d3962-689e-44e4-a998-1680f85d514f.mp4

### PR DESCRIPTION
**Pull request by ninokeldishvili**
fixes #72 
https://lucky-poetry-9761.on.fleek.co/

### CODE REVIEW

**Comment by ichniten** [comment]
testone

**Comment by ichniten** [comment]
The 'create new asset class' button should actually be disabled before something has been pasted into the schema area, this is what is t

**Comment by ichniten** [comment]
Great! The 'Create new asset class' button now starts off disabled, and when a schema is pasted in, there's one error (the red bar with the eye) When the schema I got off the internet randomly that came up with the error last time doesn't show up now, and the button is disabled test3

**Comment by ninokeldishvili** [comment]
`and the button is disabled` - part should be fixed, but can you tell me more about what happened about internet connection?

**Review by ichniten — APPROVED** [review]

**Pull request merged**
